services:
  test:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes_from:
      - cache
    links:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: $DJANGO_SETTINGS_MODULE
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      TEST_OUTPUT_DIR: $TEST_OUTPUT_DIR

  # This agent is required to poll the db server to see if a connection
  # can be established before running the tests.
  agent:
    image: joaskramer/ansible
    volumes:
      - ../../ansible/probe.yml:/ansible/site.yml
    links:
      - 'db'
    environment:
      PROBE_HOST: 'db'
      PROBE_PORT: $MYSQL_PORT

  db:
    image: mysql:latest # The guide uses mysql:5.6
    hostname: $MYSQL_HOST
    expose:
      - $MYSQL_PORT
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

  cache:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - /tmp/cache:/cache
    entrypoint: "true"